services:
  neo4j:
    image: neo4j:latest
    container_name: SIM3-DB
    environment:
      - NEO4J_AUTH=neo4j/sim3P@ss0rD123
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7474:7474"
      - "7687:7687"
